version: '3.4'
services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    # container_name: mysql
    ports:
      - "3306:3306"
      - "49159:33060"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: 'mysql'
      PMA_USER: 'root'
      PMA_PASSWORD: 'password'
    volumes:
      - /sessions
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
    ports:
      - "8090:80"
    networks:
      - default

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./redis_data:/data"
    restart: always

  # nginx:
  #   # image: nginx:1.15.6
  #   image: nginx
  #   # image: nginx:1.18
  #   ports:
  #     - "8091:80"
  #   volumes:
  #     # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     # - ./docker/nginx/static.conf:/etc/nginx/conf.d/default.conf #host volume
  #     # # - ./public:/usr/share/nginx/html
  #     # - ./nginx/html:/usr/share/nginx/html:ro
  #     # - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/html:/var/www/html
  #   restart: always


  ngrok:
    image: wernight/ngrok
    ports:
      - 4040:4040
    environment:
      # - NGROK_PORT=h2o:443
      NGROK_PROTOCOL: http
      NGROK_PORT: 80
      # NGROK_PORT: ai-brid.local
      # NGROK_PORT: local:80
      NGROK_REGION: ap
      NGROK_AUTH: 1n2xr1quXUbnG71lKdHVegHbN1C_APcXvXf4bE9qquuNdBUC
      NGROK_HEADER: 0.0.0.0


networks:
  default:
    external:
      name: share_network





# services:
#   # h2o:
#   #   image: lkwg82/h2o-http2-server:latest
#   #   working_dir: /etc/h2o
#   #   restart: always
#   #   ports:
#   #     - 443:443
#   #     - 80:80
#   #     - 4041:4041
#   #   volumes:
#   #     - ./docker/h2o:/etc/h2o:cached

#   # ngrok:
#   #   image: wernight/ngrok
#   #   depends_on:
#   #     - h2o
#   #   ports:
#   #     - 4040:4040
#   #   environment:
#   #     - NGROK_PORT=h2o:443

# volumes:
#   bundle-volume:
