version: "3"

services:
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.0
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms128m -Xms128m"
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
    # volumes:
    #   - elastic:/usr/share/elasticsearch/data


  kibana:
    # image: docker.elastic.co/kibana/kibana-oss:7.0.0
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      I18N_LOCALE: "ja-JP"
    depends_on:
      - elasticsearch
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml


  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.0.0
    volumes:
      - "./data/logstash/pipeline:/usr/share/logstash/pipeline"
      - "./data/nginx/log:/var/log/nginx"
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:latest
    ports:
      - "8099:80"
    volumes:
      - "./data/nginx/log:/var/log/nginx"
    depends_on:
      - logstash

volumes:
  es_data:
    driver: local